name: SafeTrade
main: net.torosamy.safeTrade.SafeTrade
version: '${project.version}'
author: '${plugin.yml.author}'
website: '${plugin.yml.website}'
api-version: '${plugin.yml.api}'
depend:
  - TorosamyCore